### PR TITLE
Refactor and add error codes

### PR DESCRIPTION
**Pull request by 64**
Ok, big commit here, apologies for this. I initially started out by trying to just add the error codes but that meant I needed to touch a lot of code in order to do so. Regardless I think it was a good idea to do this now rather than later on, before we run into any issues.

Firstly, I added an enum which describes all the error codes which we might run into, including internal errors. This allows functions to indicate if it succeeded (i.e it returned E_NONE which is equal to zero) or if it failed (it returned another tx_err value as defined in err.h).

I renamed the error handling functions because I didn't believe they were accurate: `tx_gl_error_callback` now becomes `tx_glfw_error_callback`, `tx_gl_geterr` becomes `tx_geterr` again (because it handles GLFW and OpenGL errors while also checking to see if the error log is clear alltogether) and `tx_gl_print_errors` now becomes `tx_print_errors` again too (because it prints any sort of error that might find itself in the error log).

Secondly, I extracted a couple of FreeType functions into `font.c`, because we're probably going to need that eventually even if not right now.

One current thing to note is that the path to the font at `/usr/share/fonts/corefonts/arial.ttf` isn't vaild on either of the systems I tried (OSX, Ubuntu). Obviously it is just temporary but it still means that I can't test things out, so we may want to change that.

Sorry for the wall of text, I should be able to get started on the OpenGL rendering stuff today or tomorrow.

Let me know if there are any issues.

### CODE REVIEW

**Comment by Bfgeshka** [comment]
Looks like now this PR has unresolved merging conflicts.

**Comment by desolt** [comment]
@Bfgeshka probably my fault when running `make format` on everything in one of my commits.

**Comment by 64** [comment]
Let me just check that actually compiles now...

**Comment by Bfgeshka** [comment]
@desolt  It's mostly my fault because I didn't run it after changing astyle config.

**Comment by 64** [comment]
Compiles fine here (with a couple of unused variable warnings from @desolt's PR, but nothing to worry about).

**Pull request merged**
