### PR TITLE
Add unit testing

### PR DESCRIPTION
**Pull request by 64**
Firstly, this builds termix as a shared library, which allows the test executables to be linked and run on their own. I have also added a small test runner script which runs all the tests and displays stdout from any failing tests and sets the exit code accordingly. You can compile and run the tests with `make test`.

Closes https://github.com/Bfgeshka/termix/issues/13

### CODE REVIEW

**Comment by Bfgeshka** [comment]
Please make distiction between debug/test build and working build. Add target for release which will compile termix as normal application without `-fPIC` and for test which builds with test coverage and debug symbols.

**Comment by 64** [comment]
Will do - but what do you mean "builds with test coverage"? Do you mean including the `test` target as part of the default (`all`) target?

**Comment by 64** [comment]
Now you can build in release mode by doing `NDEBUG=1 make`.

**Comment by Bfgeshka** [comment]
That'll do, I guess. Changes are pretty massive, so I'll accept it as is for now.

**Pull request merged**
